### PR TITLE
Add a suffix to the stacks to easily identify Python stacks

### PR DESCRIPTION
**Pull request by alonbentamar**

### CODE REVIEW

**Comment by alonbentamar** [comment]
Testing it

**Comment by Jongy** [comment]
@alonbentamar can this be merged? Make sure to squash and merge, and rebase on 0.3.7g1.

**Comment by alonbentamar** [comment]
> @alonbentamar can this be merged? Make sure to squash and merge, and rebase on 0.3.7g1.

Can be merged, the backend is ready. The branch is already up-to-date.

**Comment by Jongy** [comment]
Your commit is based on 0a1f4ca330a2dad98f10db9f198da9ce5187af48 and in any case should not be merged to "master" but to a branch based on v0.3.7g1 which is 3837a0a76ccf2d3328100f9e47a25de3b5d9e9eb.

**Comment by alonbentamar** [comment]
@Jongy Changed it, is this okay now?

**Review by Jongy — APPROVED** [review]
LGTM, squash and merge it

**Pull request merged**
